### ISSUE TITLE
Calling variables within jsx

### ISSUE THREAD

**Issue by amykuner** [fac22/week6-EMJA#45]
Instead of using {`${variable}'}, you can just use {variable} - inside the curly brackets is already javascript so you don't need to use a template literal

https://github.com/fac22/week6-EMJA/blob/9faafaa929aa2482aaf11d47ef7fc5fe95936e9d/pages/products/%5Bid%5D.js#L79

**Comment by Alisyad9** [comment]
Thanks @amykuner, refactored it  including some other once.
