### ISSUE TITLE
Commented code and console logs

### ISSUE THREAD

**Issue by amykuner** [fac22/week6-EMJA#47]
I know you probably ran out of time but it's always best to remove all commented out code and console logs that aren't doing anything before you push to main! 

I saw a couple just in this file:

https://github.com/fac22/week6-EMJA/blob/9faafaa929aa2482aaf11d47ef7fc5fe95936e9d/pages/products/%5Bid%5D.js#L3

(lines 3 and 82)

**Comment by amykuner** [comment]
Also, delete empty or unused files (e.g hello.js, data.json, size-picker.module.css)

**Comment by Alisyad9** [comment]
Deleted the empty files that we are not using, also got rid of the commented codes except for the cypress once. Because they are there to better understand the code. Thanks @amykuner
