### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by amykuner** [fac22/week6-EMJA#55]
When you set the filter to between £2.75 and £3.50, the tiramisu cake somehow sneaks its way in even though it costs £2.50

**Comment by amykuner** [comment]
Oh wait, there are multiple that sneak through!

**Comment by amykuner** [comment]
Okay, I think I'm confusing myself because it looks like there are 2 sets of cakes being added here - one below the price filter and one below the categories filter. They look like they have some overlap but they're not completely the same?

**Comment by Moggach** [comment]
I think this is because I have two sets of products and filters acting independently - which is confusing. I am going to try to refactor this.
