### ISSUE TITLE
Cakes get squished

### ISSUE THREAD

**Issue by lopezelpesado** [fac22/week6-EMJA#63]
On smaller width displays, like older phones, the cakes start looking a bit squished. Might need to change how you are setting their width and height to make sure you're maintaining aspect ratio

![image](https://user-images.githubusercontent.com/76691426/140495344-88cdfff4-d3e9-48f9-bf51-ff8f1874ea62.png)

**Comment by elenamarinaki** [comment]
Will try to fix this Alex, thanks for pointing it out ;) I am not sure we have the same dimensions in all images, so the rules do not apply exactly the same 🤔
